# 002 - llm_resume_grader/config.yaml
llm:
  model: "gpt-4.1-mini-2025-04-14"

  params:
    temperature: 0.2
    top_p: 1.0
    frequency_penalty: 0
    presence_penalty: 0
    max_tokens: 1000

  retry_max: 6

grading:
  scale: {A: 4, B: 3, C: 2, D: 1}


paths:
  candidates_glob: "data/input/candidates/*.md"
  system_prompt:    "data/input/system_prompt.md"
  out_json:         "data/output/results.json"
  out_md_summary:   "data/output/results_summary.md"
  out_md_full:      "data/output/results_full.md"
  candidate_md_dir: "data/output/candidates_md"